name: "pipeline-rds"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Plan:
    uses: ./.github/workflows/aws_tf_plan.yml
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: ./.github/workflows/aws_tf_appy.yml
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
